name = "hyde-hyde"
license = "MIT"
licenselink = "https://github.com/frigginglorious/hyde-hyde/blob/master/LICENSE.md"
description = "A simply cool Hyde inspired theme"
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "disqus", "graphcomment", "portfolio"]
homepage = "https://github.com/frigginglorious/hyde-hyde"
min_version = "0.43"

[author]
    name = "frigginGlorious"
    homepage = "https://frigginglorious.github.io"

# Ported from a theme by htr3n
[original]
    author =  "spf13"
    homepage = "http://spf13.com/"
    repo = "https://github.com/spf13/hyde"
